version: '3.9'

services:
  
  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: backend
    ports:
      - '8000:8000'
    env_file:
      - .env

  worker:
    build:
      context: ./llm_integration
      dockerfile: Dockerfile
    container_name: worker
    env_file:
      - .env
    

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '8502:8502'
    depends_on:
      - backend
